# docker-compose.yml
networks:
  n8n-clarify-net:
    name: n8n-clarify-net
    driver: bridge

volumes:
  n8n-data:
  ollama-data:
  pgdata:
  evolution_store:
  evolution_instances:
  evolution-audio: 

services:
  n8n-clarify-core:
    image: n8nio/n8n
    container_name: n8n-Clarify-n8n
    ports: ["5678:5678"]
    networks: [n8n-clarify-net]
    volumes:
      - n8n-data:/home/node/.n8n
      - ./tmp/news:/tmp/news
    env_file: .env
    depends_on:
      - postgree
      - llm-ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  llm-ollama:
    image: ollama/ollama
    container_name: n8n-Clarify-Ollama
    ports: ["11434:11434"]
    networks: [n8n-clarify-net]
    volumes:
      - ollama-data:/models
      - ollama-data:/root/.ollama
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgree:
    image: postgres:16
    container_name: n8n-Clarify-DB
    ports: ["5432:5432"]
    networks: [n8n-clarify-net]
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: n8n-Clarify-EvolutionAPI
    ports:
      - "8085:8080"
    networks: [n8n-clarify-net]
    volumes:
      - evolution-audio:/app/audios
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    env_file: .env
    environment:
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1023204200
      - LICENSE_KEY=${EVOLUTION_LICENSE_KEY}
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - INTERFACE=all
      - WEBHOOK_URL_EVO=${WEBHOOK_URL_EVO}
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgree:5432/${POSTGRES_DB}?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=n8nClarifyEvolutionClient
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
    depends_on:
      - postgree
    restart: unless-stopped
